### ISSUE TITLE
possible bug with transposing certain objects?

### ISSUE THREAD

**Issue by blord-fullscreen** [henrytseng/dataobject-parser#9]
I'm noticing a recent breaking change. I'm not sure if this is a bug or expected behavior. I've isolated it down to this example:

In 1.1.3:

    dataObjectParser.transpose({ "links[]": null })._data; // returns {}

In 1.2.1, current latest:

    dataObjectParser.transpose({"links[]": null})._data; // returns { "links": [null] }

Thanks for any clarification on what to expect here.

**Comment by henrytseng** [comment]
Expected functionality should be 1.2.1 response.  Looks like earlier version did not respond correctly.  I think `null` values should be preserved.  

Please let me know if there's reason to revert otherwise?

**Comment by henrytseng** [comment]
I'm going to close this issue unless if someone would like to contest this view.  If you disagree, of course, please explain and show some examples of why it should work otherwise from how it does now.  As far as I'm concerned this should be the correct functionality moving forward -- that is it will explicitly store `null` values.
